### ISSUE TITLE
emoji.h5

### ISSUE THREAD

**Issue by niallomahony93** [uwdata/latent-space-cartography#24]
The file emoji.h5 which is referencsd in model/train.py is not included. Is it available to download?

**Comment by yyyliu** [comment]
Sorry for the delay. The file `emoji.h5` might be found inside this large zip archive: 
https://drive.google.com/file/d/138hiSwsjE3WSn7XRX9TcCSsrqtx89bJi/view?usp=sharing

**Comment by niallomahony93** [comment]
Thank you
