### ISSUE TITLE
Permission to use Figure from your paper

### ISSUE THREAD

**Issue by niallomahony93** [uwdata/latent-space-cartography#27]
Can you grant me permission to reproduce figure 1 (c) of your paper ' Latent Space Cartography:
Visual Analysis of Vector Space Embeddings' please.

It will be published in my review paper ' Representation Learning for Fine-Grained Change Detection'  to be published in MDPIs sensors journal. 

A prompt reply would be much appreciated.

**Comment by yyyliu** [comment]
Yes you have my permission! Thanks for your interest in our paper.
